"""initial clean schema

Revision ID: 8ad6359b8702
Revises: 
Create Date: 2026-02-24 13:17:33.070981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ad6359b8702'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # =================================================================
    # PostgreSQL Sequences for unique number generation
    # =================================================================
    # These sequences ensure thread-safe, atomic generation of unique
    # identifiers for patients, appointments, and bills.
    #
    # Benefits:
    # - Guaranteed uniqueness under concurrent access
    # - No gaps under normal operation
    # - Atomic increment operation (production-safe)
    # =================================================================

    # MR Number Sequence: Medical Record numbers (MR-00001, MR-00002, etc.)
    # Used by: patient_repository.py -> generate_mr_number()
    op.execute("""
        CREATE SEQUENCE IF NOT EXISTS mr_number_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        NO CYCLE
    """)

    # OP Number Sequence: Outpatient numbers (OP-YYYYMMDD-001, OP-YYYYMMDD-002, etc.)
    # Used by: appointment_repository.py -> generate_op_number()
    # Note: Sequence provides the numeric part; date prefix added in code
    op.execute("""
        CREATE SEQUENCE IF NOT EXISTS op_number_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        NO CYCLE
    """)

    # Bill Number Sequence: Bill numbers (BLL-YYYYMMDD-0001, BLL-YYYYMMDD-0002, etc.)
    # Used by: billing_repository.py -> generate_bill_number()
    # Note: Sequence provides the numeric part; date prefix added in code
    op.execute("""
        CREATE SEQUENCE IF NOT EXISTS bill_number_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        NO CYCLE
    """)

    op.create_table('departments',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Department name (e.g., Cardiology)'),
    sa.Column('code', sa.String(length=20), nullable=False, comment='Short code (e.g., CARD)'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Department description'),
    sa.Column('base_consultation_fee', sa.Numeric(precision=10, scale=2), nullable=False, comment='Default consultation fee for this department'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether department is active'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.create_index(op.f('ix_departments_created_at'), 'departments', ['created_at'], unique=False)
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_is_active'), 'departments', ['is_active'], unique=False)
    op.create_index(op.f('ix_departments_is_deleted'), 'departments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_table('medicine_master',
    sa.Column('code', sa.String(length=50), nullable=False, comment='Medicine code (unique per specialization)'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Medicine brand name'),
    sa.Column('generic_name', sa.String(length=255), nullable=True, comment='Generic/chemical name'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='Medicine category (e.g., Blood Pressure, CAD)'),
    sa.Column('specialization', sa.String(length=100), nullable=False, comment='Medical specialization (e.g., Cardiology)'),
    sa.Column('dosage_form', sa.String(length=50), nullable=True, comment='Form of medicine (Tablet, Capsule, etc.)'),
    sa.Column('strength', sa.String(length=50), nullable=True, comment='Strength/dosage (e.g., 5mg, 10ml)'),
    sa.Column('manufacturer', sa.String(length=200), nullable=True, comment='Manufacturer name'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether medicine is currently available'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'specialization', name='uq_medicine_code_specialization')
    )
    op.create_index(op.f('ix_medicine_master_category'), 'medicine_master', ['category'], unique=False)
    op.create_index('ix_medicine_master_category_spec', 'medicine_master', ['category', 'specialization'], unique=False)
    op.create_index(op.f('ix_medicine_master_code'), 'medicine_master', ['code'], unique=False)
    op.create_index('ix_medicine_master_code_spec', 'medicine_master', ['code', 'specialization'], unique=False)
    op.create_index(op.f('ix_medicine_master_created_at'), 'medicine_master', ['created_at'], unique=False)
    op.create_index(op.f('ix_medicine_master_id'), 'medicine_master', ['id'], unique=False)
    op.create_index(op.f('ix_medicine_master_is_active'), 'medicine_master', ['is_active'], unique=False)
    op.create_index(op.f('ix_medicine_master_is_deleted'), 'medicine_master', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_medicine_master_name'), 'medicine_master', ['name'], unique=False)
    op.create_index('ix_medicine_master_name_active', 'medicine_master', ['name', 'is_active'], unique=False)
    op.create_index(op.f('ix_medicine_master_specialization'), 'medicine_master', ['specialization'], unique=False)
    op.create_table('op_complaints_master',
    sa.Column('code', sa.String(length=50), nullable=False, comment='Unique complaint code'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='Broad category of the complaint'),
    sa.Column('complaint', sa.String(length=255), nullable=False, comment='The complaint description'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_op_complaints_master_category'), 'op_complaints_master', ['category'], unique=False)
    op.create_index(op.f('ix_op_complaints_master_code'), 'op_complaints_master', ['code'], unique=True)
    op.create_index(op.f('ix_op_complaints_master_complaint'), 'op_complaints_master', ['complaint'], unique=False)
    op.create_index(op.f('ix_op_complaints_master_created_at'), 'op_complaints_master', ['created_at'], unique=False)
    op.create_index(op.f('ix_op_complaints_master_id'), 'op_complaints_master', ['id'], unique=False)
    op.create_index(op.f('ix_op_complaints_master_is_deleted'), 'op_complaints_master', ['is_deleted'], unique=False)
    op.create_table('op_diagnosis_master',
    sa.Column('code', sa.String(length=50), nullable=False, comment='Unique diagnosis code'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='Broad category of the diagnosis'),
    sa.Column('diagnosis', sa.String(length=255), nullable=False, comment='The diagnosis description'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_op_diagnosis_master_category'), 'op_diagnosis_master', ['category'], unique=False)
    op.create_index(op.f('ix_op_diagnosis_master_code'), 'op_diagnosis_master', ['code'], unique=True)
    op.create_index(op.f('ix_op_diagnosis_master_created_at'), 'op_diagnosis_master', ['created_at'], unique=False)
    op.create_index(op.f('ix_op_diagnosis_master_diagnosis'), 'op_diagnosis_master', ['diagnosis'], unique=False)
    op.create_index(op.f('ix_op_diagnosis_master_id'), 'op_diagnosis_master', ['id'], unique=False)
    op.create_index(op.f('ix_op_diagnosis_master_is_deleted'), 'op_diagnosis_master', ['is_deleted'], unique=False)
    op.create_table('op_labtests_master',
    sa.Column('code', sa.String(length=50), nullable=False, comment='Unique lab test code'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='Broad category of the lab test'),
    sa.Column('test_name', sa.String(length=255), nullable=False, comment='The lab test name'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_op_labtests_master_category'), 'op_labtests_master', ['category'], unique=False)
    op.create_index(op.f('ix_op_labtests_master_code'), 'op_labtests_master', ['code'], unique=True)
    op.create_index(op.f('ix_op_labtests_master_created_at'), 'op_labtests_master', ['created_at'], unique=False)
    op.create_index(op.f('ix_op_labtests_master_id'), 'op_labtests_master', ['id'], unique=False)
    op.create_index(op.f('ix_op_labtests_master_is_deleted'), 'op_labtests_master', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_op_labtests_master_test_name'), 'op_labtests_master', ['test_name'], unique=False)
    op.create_table('patients',
    sa.Column('mr_number', sa.String(length=20), nullable=False, comment='Medical Record Number (MR-XXXXX format)'),
    sa.Column('first_name', sa.String(length=100), nullable=False, comment='Patient first name'),
    sa.Column('last_name', sa.String(length=100), nullable=False, comment='Patient last name'),
    sa.Column('date_of_birth', sa.Date(), nullable=True, comment='Date of birth'),
    sa.Column('gender', sa.Enum('Male', 'Female', 'Other', name='gender_enum', native_enum=False), nullable=False, comment='Patient gender'),
    sa.Column('marital_status', sa.Enum('Single', 'Married', 'Divorced', 'Widowed', name='marital_status_enum', native_enum=False), nullable=True, comment='Marital status'),
    sa.Column('patient_type', sa.Enum('New', 'Review', 'Emergency', 'Referral', name='patient_type_enum', native_enum=False), nullable=True, comment='Patient type'),
    sa.Column('phone', sa.String(length=15), nullable=False, comment='Primary phone (Indian format)'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Email address'),
    sa.Column('emergency_contact', sa.String(length=15), nullable=True, comment='Emergency contact phone'),
    sa.Column('address', sa.Text(), nullable=True, comment='Street address'),
    sa.Column('city', sa.String(length=100), nullable=True, comment='City'),
    sa.Column('state', sa.String(length=100), nullable=True, comment='State'),
    sa.Column('pin_code', sa.String(length=10), nullable=True, comment='PIN code'),
    sa.Column('blood_group', sa.String(length=10), nullable=True, comment='Blood group'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_created_at'), 'patients', ['created_at'], unique=False)
    op.create_index(op.f('ix_patients_email'), 'patients', ['email'], unique=False)
    op.create_index(op.f('ix_patients_first_name'), 'patients', ['first_name'], unique=False)
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_index(op.f('ix_patients_is_deleted'), 'patients', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_patients_last_name'), 'patients', ['last_name'], unique=False)
    op.create_index(op.f('ix_patients_mr_number'), 'patients', ['mr_number'], unique=True)
    op.create_index(op.f('ix_patients_phone'), 'patients', ['phone'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False, comment='Unique login identifier'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Bcrypt hashed password'),
    sa.Column('display_name', sa.String(length=200), nullable=False, comment='Name displayed in UI header'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Optional email for notifications'),
    sa.Column('role', sa.Enum('admin', 'front-office', 'doctor', name='user_role', native_enum=False), nullable=False, comment='User role determining access permissions'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether account is active and can login'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last successful login'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index('ix_users_role_active', 'users', ['role', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index('ix_users_username_active', 'users', ['username', 'is_active'], unique=False)
    op.create_table('doctors',
    sa.Column('user_id', sa.UUID(), nullable=True, comment='Link to user account for authentication'),
    sa.Column('department_id', sa.UUID(), nullable=True, comment="Doctor's primary department"),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Full name with title (e.g., Dr. R. Balaji)'),
    sa.Column('speciality', sa.String(length=100), nullable=True, comment='Medical speciality'),
    sa.Column('qualification', sa.String(length=200), nullable=True, comment='Medical qualifications (e.g., MBBS, MD)'),
    sa.Column('registration_number', sa.String(length=50), nullable=True, comment='Medical council registration number'),
    sa.Column('phone', sa.String(length=15), nullable=True, comment='Contact phone number'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Professional email'),
    sa.Column('room', sa.String(length=20), nullable=True, comment='Default consultation room'),
    sa.Column('consultation_fee', sa.Numeric(precision=10, scale=2), nullable=True, comment='Override consultation fee (null = use department fee)'),
    sa.Column('is_available', sa.Boolean(), nullable=False, comment='Whether doctor is currently available for consultations'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_index(op.f('ix_doctors_created_at'), 'doctors', ['created_at'], unique=False)
    op.create_index(op.f('ix_doctors_department_id'), 'doctors', ['department_id'], unique=False)
    op.create_index(op.f('ix_doctors_id'), 'doctors', ['id'], unique=False)
    op.create_index(op.f('ix_doctors_is_available'), 'doctors', ['is_available'], unique=False)
    op.create_index(op.f('ix_doctors_is_deleted'), 'doctors', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_doctors_name'), 'doctors', ['name'], unique=False)
    op.create_index(op.f('ix_doctors_user_id'), 'doctors', ['user_id'], unique=True)
    op.create_table('appointments',
    sa.Column('op_number', sa.String(length=20), nullable=False, comment='Outpatient Number (OP-YYYYMMDD-XXX format)'),
    sa.Column('patient_id', sa.UUID(), nullable=False, comment='Link to patient'),
    sa.Column('doctor_id', sa.UUID(), nullable=True, comment='Assigned doctor'),
    sa.Column('appointment_date', sa.Date(), nullable=False, comment='Appointment date'),
    sa.Column('appointment_time', sa.Time(), nullable=True, comment='Scheduled appointment time'),
    sa.Column('token_number', sa.Integer(), nullable=False, comment='Daily token/queue number'),
    sa.Column('status', sa.Enum('waiting', 'in-progress', 'completed', 'cancelled', name='appointment_status_enum', native_enum=False), nullable=False, comment='Current appointment status'),
    sa.Column('queue_type', sa.Enum('main', 'lab', 'pharmacy', name='queue_type_enum', native_enum=False), nullable=False, comment='Which queue this appointment is in'),
    sa.Column('room', sa.String(length=20), nullable=True, comment='Consultation room number'),
    sa.Column('waiting_time_minutes', sa.Integer(), nullable=True, comment='Calculated waiting time in minutes (based on queue position)'),
    sa.Column('buffer_time_minutes', sa.Integer(), nullable=True, comment="Extra buffer time added to this patient's consultation slot"),
    sa.Column('eta_started_at', sa.String(length=50), nullable=True, comment='Timestamp when ETA calculation was last performed (ISO format)'),
    sa.Column('called_at', sa.String(length=50), nullable=True, comment='When patient was called (status → in-progress)'),
    sa.Column('completed_at', sa.String(length=50), nullable=True, comment='When consultation completed'),
    sa.Column('announcement_played', sa.Boolean(), nullable=False, comment='Whether the TV announcement has been played for this patient'),
    sa.Column('announcement_played_at', sa.String(length=50), nullable=True, comment='When the announcement was played (ISO format)'),
    sa.Column('notes', sa.String(length=500), nullable=True, comment='Additional notes'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_created_at'), 'appointments', ['created_at'], unique=False)
    op.create_index('ix_appointments_date_status', 'appointments', ['appointment_date', 'status'], unique=False)
    op.create_index('ix_appointments_doctor_date', 'appointments', ['doctor_id', 'appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_index(op.f('ix_appointments_is_deleted'), 'appointments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_appointments_op_number'), 'appointments', ['op_number'], unique=True)
    op.create_index('ix_appointments_patient_date', 'appointments', ['patient_id', 'appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_table('bills',
    sa.Column('bill_number', sa.String(length=20), nullable=False, comment='Bill number (BLL-YYYYMMDD-XXX format)'),
    sa.Column('appointment_id', sa.UUID(), nullable=True, comment='Link to appointment'),
    sa.Column('patient_id', sa.UUID(), nullable=False, comment='Link to patient'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='Staff who created the bill'),
    sa.Column('uhid', sa.String(length=50), nullable=True, comment='Unique Hospital ID'),
    sa.Column('patient_name', sa.String(length=200), nullable=False, comment='Patient name for receipt'),
    sa.Column('patient_age', sa.String(length=10), nullable=True, comment='Patient age for receipt'),
    sa.Column('patient_gender', sa.String(length=10), nullable=True, comment='Patient gender for receipt'),
    sa.Column('doctor_name', sa.String(length=200), nullable=True, comment='Doctor name for receipt'),
    sa.Column('speciality', sa.String(length=100), nullable=True, comment='Department/speciality'),
    sa.Column('mobile_no', sa.String(length=15), nullable=True, comment='Patient mobile for receipt'),
    sa.Column('patient_type', sa.String(length=50), nullable=True, comment='Patient type'),
    sa.Column('token_number', sa.String(length=20), nullable=True, comment='Token/OP number'),
    sa.Column('consultation_fee', sa.Numeric(precision=10, scale=2), nullable=False, comment='Consultation fee'),
    sa.Column('other_charges', sa.String(length=200), nullable=True, comment='Description of other charges'),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False, comment='Subtotal before discount'),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Discount amount'),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False, comment='Discount percentage'),
    sa.Column('discount_given_by', sa.String(length=100), nullable=True, comment='Who authorized the discount'),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Total amount after discount'),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Amount paid'),
    sa.Column('due_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Amount due'),
    sa.Column('payment_status', sa.Enum('pending', 'partial', 'paid', name='payment_status_enum', native_enum=False), nullable=False, comment='Payment status'),
    sa.Column('payment_method', sa.Enum('cash', 'card', 'upi', name='payment_method_enum', native_enum=False), nullable=True, comment='Payment method used'),
    sa.Column('payment_reference', sa.String(length=100), nullable=True, comment='Transaction reference number'),
    sa.Column('insurance_provider', sa.String(length=100), nullable=True, comment='Insurance provider name'),
    sa.Column('insurance_policy_number', sa.String(length=100), nullable=True, comment='Insurance policy number'),
    sa.Column('lab_total', sa.Numeric(precision=10, scale=2), nullable=False, comment='Total amount of lab/investigation items'),
    sa.Column('lab_and_investigations', sa.Text(), nullable=True, comment='JSON array of lab items: [{name, amount}]'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bills_appointment_id'), 'bills', ['appointment_id'], unique=True)
    op.create_index(op.f('ix_bills_bill_number'), 'bills', ['bill_number'], unique=True)
    op.create_index(op.f('ix_bills_created_at'), 'bills', ['created_at'], unique=False)
    op.create_index('ix_bills_created_at_status', 'bills', ['created_at', 'payment_status'], unique=False)
    op.create_index(op.f('ix_bills_id'), 'bills', ['id'], unique=False)
    op.create_index(op.f('ix_bills_is_deleted'), 'bills', ['is_deleted'], unique=False)
    op.create_index('ix_bills_patient_created', 'bills', ['patient_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_bills_patient_id'), 'bills', ['patient_id'], unique=False)
    op.create_index(op.f('ix_bills_payment_status'), 'bills', ['payment_status'], unique=False)
    op.create_table('lab_queue_items',
    sa.Column('appointment_id', sa.UUID(), nullable=False, comment='Link to appointment'),
    sa.Column('patient_id', sa.UUID(), nullable=False, comment='Link to patient'),
    sa.Column('patient_name', sa.String(length=200), nullable=False, comment='Patient name for display'),
    sa.Column('mr_number', sa.String(length=20), nullable=False, comment='MR number for display'),
    sa.Column('op_number', sa.String(length=20), nullable=False, comment='OP number for display'),
    sa.Column('token_number', sa.Integer(), nullable=False, comment='Lab queue token number'),
    sa.Column('lab_tests', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='List of lab tests to perform'),
    sa.Column('status', sa.Enum('pending', 'waiting', 'in-progress', 'completed', 'cancelled', name='queue_status_enum', native_enum=False), nullable=False, comment='Queue item status'),
    sa.Column('collected_at', sa.String(length=50), nullable=True, comment='When sample was collected'),
    sa.Column('completed_at', sa.String(length=50), nullable=True, comment='When results were ready'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lab_queue_created_status', 'lab_queue_items', ['created_at', 'status'], unique=False)
    op.create_index(op.f('ix_lab_queue_items_appointment_id'), 'lab_queue_items', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_lab_queue_items_created_at'), 'lab_queue_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_lab_queue_items_id'), 'lab_queue_items', ['id'], unique=False)
    op.create_index(op.f('ix_lab_queue_items_is_deleted'), 'lab_queue_items', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_lab_queue_items_patient_id'), 'lab_queue_items', ['patient_id'], unique=False)
    op.create_index(op.f('ix_lab_queue_items_status'), 'lab_queue_items', ['status'], unique=False)
    op.create_table('patient_documents',
    sa.Column('patient_id', sa.UUID(), nullable=False, comment='Link to patient'),
    sa.Column('appointment_id', sa.UUID(), nullable=True, comment='Optional link to appointment'),
    sa.Column('uploaded_by', sa.UUID(), nullable=True, comment='User who uploaded the document'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='Original file name'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='Storage path or URL'),
    sa.Column('file_type', sa.String(length=100), nullable=False, comment='MIME type'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='File size in bytes'),
    sa.Column('document_type', sa.String(length=100), nullable=True, comment='Document category (lab report, prescription, etc.)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Document description'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_documents_appointment_id'), 'patient_documents', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_patient_documents_created_at'), 'patient_documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_patient_documents_id'), 'patient_documents', ['id'], unique=False)
    op.create_index(op.f('ix_patient_documents_is_deleted'), 'patient_documents', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_patient_documents_patient_id'), 'patient_documents', ['patient_id'], unique=False)
    op.create_table('patient_vitals',
    sa.Column('appointment_id', sa.UUID(), nullable=False, comment='Link to appointment'),
    sa.Column('patient_id', sa.UUID(), nullable=False, comment='Link to patient'),
    sa.Column('recorded_by', sa.UUID(), nullable=True, comment='Staff who recorded vitals'),
    sa.Column('spo2', sa.Integer(), nullable=True, comment='Oxygen saturation percentage'),
    sa.Column('pulse', sa.Integer(), nullable=False, comment='Pulse rate (beats per minute)'),
    sa.Column('blood_pressure', sa.String(length=20), nullable=False, comment='Blood pressure (format: systolic/diastolic)'),
    sa.Column('cvs', sa.String(length=100), nullable=True, comment='Cardiovascular system findings'),
    sa.Column('rs', sa.String(length=100), nullable=True, comment='Respiratory system findings'),
    sa.Column('jvp', sa.String(length=50), nullable=True, comment='Jugular venous pressure'),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True, comment='Weight in kg'),
    sa.Column('hlp', sa.String(length=50), nullable=True, comment='Hyperlipidemia status'),
    sa.Column('htn', sa.String(length=50), nullable=True, comment='Hypertension status'),
    sa.Column('dm', sa.String(length=50), nullable=True, comment='Diabetes mellitus status'),
    sa.Column('smoking', sa.String(length=50), nullable=True, comment='Smoking status'),
    sa.Column('family_ho_cad', sa.String(length=100), nullable=True, comment='Family history of coronary artery disease'),
    sa.Column('heart_disease', sa.String(length=100), nullable=True, comment='Known heart disease'),
    sa.Column('ptca_cabg', sa.String(length=100), nullable=True, comment='Previous PTCA/CABG procedures'),
    sa.Column('current_drugs', sa.Text(), nullable=True, comment='Current medications'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_vitals_appointment_id'), 'patient_vitals', ['appointment_id'], unique=True)
    op.create_index(op.f('ix_patient_vitals_created_at'), 'patient_vitals', ['created_at'], unique=False)
    op.create_index(op.f('ix_patient_vitals_id'), 'patient_vitals', ['id'], unique=False)
    op.create_index(op.f('ix_patient_vitals_is_deleted'), 'patient_vitals', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_patient_vitals_patient_id'), 'patient_vitals', ['patient_id'], unique=False)
    op.create_table('pharmacy_queue_items',
    sa.Column('appointment_id', sa.UUID(), nullable=False, comment='Link to appointment'),
    sa.Column('patient_id', sa.UUID(), nullable=False, comment='Link to patient'),
    sa.Column('patient_name', sa.String(length=200), nullable=False, comment='Patient name for display'),
    sa.Column('mr_number', sa.String(length=20), nullable=False, comment='MR number for display'),
    sa.Column('op_number', sa.String(length=20), nullable=False, comment='OP number for display'),
    sa.Column('token_number', sa.Integer(), nullable=False, comment='Pharmacy queue token number'),
    sa.Column('medicines', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='List of medicines to dispense'),
    sa.Column('status', sa.Enum('pending', 'waiting', 'in-progress', 'completed', 'cancelled', name='queue_status_enum', native_enum=False), nullable=False, comment='Queue item status'),
    sa.Column('dispensed_at', sa.String(length=50), nullable=True, comment='When medicines were dispensed'),
    sa.Column('completed_at', sa.String(length=50), nullable=True, comment='When patient collected medicines'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pharmacy_queue_created_status', 'pharmacy_queue_items', ['created_at', 'status'], unique=False)
    op.create_index(op.f('ix_pharmacy_queue_items_appointment_id'), 'pharmacy_queue_items', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_queue_items_created_at'), 'pharmacy_queue_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_pharmacy_queue_items_id'), 'pharmacy_queue_items', ['id'], unique=False)
    op.create_index(op.f('ix_pharmacy_queue_items_is_deleted'), 'pharmacy_queue_items', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_pharmacy_queue_items_patient_id'), 'pharmacy_queue_items', ['patient_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_queue_items_status'), 'pharmacy_queue_items', ['status'], unique=False)
    op.create_table('prescriptions',
    sa.Column('patient_id', sa.UUID(), nullable=False, comment='Link to patient'),
    sa.Column('appointment_id', sa.UUID(), nullable=False, comment='Link to appointment'),
    sa.Column('doctor_id', sa.UUID(), nullable=True, comment='Prescribing doctor'),
    sa.Column('diagnosis', sa.Text(), nullable=False, comment='Primary diagnosis'),
    sa.Column('complaint', sa.Text(), nullable=True, comment='Chief complaint'),
    sa.Column('history', sa.Text(), nullable=True, comment='Relevant history'),
    sa.Column('lab_tests', sa.Text(), nullable=True, comment='Ordered lab tests'),
    sa.Column('advice', sa.Text(), nullable=True, comment='Medical advice'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes'),
    sa.Column('follow_up_days', sa.Integer(), nullable=True, comment='Follow-up after X days'),
    sa.Column('sent_to_patient', sa.Boolean(), nullable=False, comment='Whether sent to patient'),
    sa.Column('sent_via', sa.String(length=20), nullable=True, comment='Delivery method (whatsapp/email)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_appointment_id'), 'prescriptions', ['appointment_id'], unique=True)
    op.create_index(op.f('ix_prescriptions_created_at'), 'prescriptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_prescriptions_doctor_id'), 'prescriptions', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_id'), 'prescriptions', ['id'], unique=False)
    op.create_index(op.f('ix_prescriptions_is_deleted'), 'prescriptions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_prescriptions_patient_id'), 'prescriptions', ['patient_id'], unique=False)
    op.create_table('bill_line_items',
    sa.Column('bill_id', sa.UUID(), nullable=False, comment='Link to parent bill'),
    sa.Column('item_type', sa.Enum('consultation', 'lab', 'pharmacy', 'procedure', 'other', name='bill_item_type_enum', native_enum=False), nullable=False, comment='Type of item'),
    sa.Column('item_name', sa.String(length=200), nullable=False, comment='Item description'),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False, comment='Quantity'),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Price per unit'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Total amount (quantity * unit_price)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_line_items_bill_id'), 'bill_line_items', ['bill_id'], unique=False)
    op.create_index(op.f('ix_bill_line_items_created_at'), 'bill_line_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_bill_line_items_id'), 'bill_line_items', ['id'], unique=False)
    op.create_index(op.f('ix_bill_line_items_is_deleted'), 'bill_line_items', ['is_deleted'], unique=False)
    op.create_table('prescription_medicines',
    sa.Column('prescription_id', sa.UUID(), nullable=False, comment='Link to prescription'),
    sa.Column('medicine_name', sa.String(length=200), nullable=False, comment='Medicine name'),
    sa.Column('dosage', sa.String(length=100), nullable=True, comment='Dosage (e.g., 10mg)'),
    sa.Column('frequency', sa.String(length=50), nullable=True, comment='Frequency (e.g., 1-0-1)'),
    sa.Column('duration', sa.String(length=50), nullable=True, comment='Duration (e.g., 30 days)'),
    sa.Column('instructions', sa.String(length=200), nullable=True, comment='Special instructions'),
    sa.Column('sequence_order', sa.Integer(), nullable=False, comment='Order in prescription'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_medicines_created_at'), 'prescription_medicines', ['created_at'], unique=False)
    op.create_index(op.f('ix_prescription_medicines_id'), 'prescription_medicines', ['id'], unique=False)
    op.create_index(op.f('ix_prescription_medicines_is_deleted'), 'prescription_medicines', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_prescription_medicines_prescription_id'), 'prescription_medicines', ['prescription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # =================================================================
    # Drop PostgreSQL Sequences
    # =================================================================
    # CASCADE ensures dependent objects are also dropped if any exist
    # IF EXISTS prevents errors if sequences were already dropped
    # =================================================================

    op.execute("DROP SEQUENCE IF EXISTS mr_number_seq CASCADE")
    op.execute("DROP SEQUENCE IF EXISTS op_number_seq CASCADE")
    op.execute("DROP SEQUENCE IF EXISTS bill_number_seq CASCADE")

    op.drop_index(op.f('ix_prescription_medicines_prescription_id'), table_name='prescription_medicines')
    op.drop_index(op.f('ix_prescription_medicines_is_deleted'), table_name='prescription_medicines')
    op.drop_index(op.f('ix_prescription_medicines_id'), table_name='prescription_medicines')
    op.drop_index(op.f('ix_prescription_medicines_created_at'), table_name='prescription_medicines')
    op.drop_table('prescription_medicines')
    op.drop_index(op.f('ix_bill_line_items_is_deleted'), table_name='bill_line_items')
    op.drop_index(op.f('ix_bill_line_items_id'), table_name='bill_line_items')
    op.drop_index(op.f('ix_bill_line_items_created_at'), table_name='bill_line_items')
    op.drop_index(op.f('ix_bill_line_items_bill_id'), table_name='bill_line_items')
    op.drop_table('bill_line_items')
    op.drop_index(op.f('ix_prescriptions_patient_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_is_deleted'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_doctor_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_created_at'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_appointment_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_pharmacy_queue_items_status'), table_name='pharmacy_queue_items')
    op.drop_index(op.f('ix_pharmacy_queue_items_patient_id'), table_name='pharmacy_queue_items')
    op.drop_index(op.f('ix_pharmacy_queue_items_is_deleted'), table_name='pharmacy_queue_items')
    op.drop_index(op.f('ix_pharmacy_queue_items_id'), table_name='pharmacy_queue_items')
    op.drop_index(op.f('ix_pharmacy_queue_items_created_at'), table_name='pharmacy_queue_items')
    op.drop_index(op.f('ix_pharmacy_queue_items_appointment_id'), table_name='pharmacy_queue_items')
    op.drop_index('ix_pharmacy_queue_created_status', table_name='pharmacy_queue_items')
    op.drop_table('pharmacy_queue_items')
    op.drop_index(op.f('ix_patient_vitals_patient_id'), table_name='patient_vitals')
    op.drop_index(op.f('ix_patient_vitals_is_deleted'), table_name='patient_vitals')
    op.drop_index(op.f('ix_patient_vitals_id'), table_name='patient_vitals')
    op.drop_index(op.f('ix_patient_vitals_created_at'), table_name='patient_vitals')
    op.drop_index(op.f('ix_patient_vitals_appointment_id'), table_name='patient_vitals')
    op.drop_table('patient_vitals')
    op.drop_index(op.f('ix_patient_documents_patient_id'), table_name='patient_documents')
    op.drop_index(op.f('ix_patient_documents_is_deleted'), table_name='patient_documents')
    op.drop_index(op.f('ix_patient_documents_id'), table_name='patient_documents')
    op.drop_index(op.f('ix_patient_documents_created_at'), table_name='patient_documents')
    op.drop_index(op.f('ix_patient_documents_appointment_id'), table_name='patient_documents')
    op.drop_table('patient_documents')
    op.drop_index(op.f('ix_lab_queue_items_status'), table_name='lab_queue_items')
    op.drop_index(op.f('ix_lab_queue_items_patient_id'), table_name='lab_queue_items')
    op.drop_index(op.f('ix_lab_queue_items_is_deleted'), table_name='lab_queue_items')
    op.drop_index(op.f('ix_lab_queue_items_id'), table_name='lab_queue_items')
    op.drop_index(op.f('ix_lab_queue_items_created_at'), table_name='lab_queue_items')
    op.drop_index(op.f('ix_lab_queue_items_appointment_id'), table_name='lab_queue_items')
    op.drop_index('ix_lab_queue_created_status', table_name='lab_queue_items')
    op.drop_table('lab_queue_items')
    op.drop_index(op.f('ix_bills_payment_status'), table_name='bills')
    op.drop_index(op.f('ix_bills_patient_id'), table_name='bills')
    op.drop_index('ix_bills_patient_created', table_name='bills')
    op.drop_index(op.f('ix_bills_is_deleted'), table_name='bills')
    op.drop_index(op.f('ix_bills_id'), table_name='bills')
    op.drop_index('ix_bills_created_at_status', table_name='bills')
    op.drop_index(op.f('ix_bills_created_at'), table_name='bills')
    op.drop_index(op.f('ix_bills_bill_number'), table_name='bills')
    op.drop_index(op.f('ix_bills_appointment_id'), table_name='bills')
    op.drop_table('bills')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index('ix_appointments_patient_date', table_name='appointments')
    op.drop_index(op.f('ix_appointments_op_number'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_is_deleted'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_index('ix_appointments_doctor_date', table_name='appointments')
    op.drop_index('ix_appointments_date_status', table_name='appointments')
    op.drop_index(op.f('ix_appointments_created_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_date'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_doctors_user_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_name'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_is_deleted'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_is_available'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_department_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_created_at'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index('ix_users_username_active', table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('ix_users_role_active', table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patients_phone'), table_name='patients')
    op.drop_index(op.f('ix_patients_mr_number'), table_name='patients')
    op.drop_index(op.f('ix_patients_last_name'), table_name='patients')
    op.drop_index(op.f('ix_patients_is_deleted'), table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_first_name'), table_name='patients')
    op.drop_index(op.f('ix_patients_email'), table_name='patients')
    op.drop_index(op.f('ix_patients_created_at'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_op_labtests_master_test_name'), table_name='op_labtests_master')
    op.drop_index(op.f('ix_op_labtests_master_is_deleted'), table_name='op_labtests_master')
    op.drop_index(op.f('ix_op_labtests_master_id'), table_name='op_labtests_master')
    op.drop_index(op.f('ix_op_labtests_master_created_at'), table_name='op_labtests_master')
    op.drop_index(op.f('ix_op_labtests_master_code'), table_name='op_labtests_master')
    op.drop_index(op.f('ix_op_labtests_master_category'), table_name='op_labtests_master')
    op.drop_table('op_labtests_master')
    op.drop_index(op.f('ix_op_diagnosis_master_is_deleted'), table_name='op_diagnosis_master')
    op.drop_index(op.f('ix_op_diagnosis_master_id'), table_name='op_diagnosis_master')
    op.drop_index(op.f('ix_op_diagnosis_master_diagnosis'), table_name='op_diagnosis_master')
    op.drop_index(op.f('ix_op_diagnosis_master_created_at'), table_name='op_diagnosis_master')
    op.drop_index(op.f('ix_op_diagnosis_master_code'), table_name='op_diagnosis_master')
    op.drop_index(op.f('ix_op_diagnosis_master_category'), table_name='op_diagnosis_master')
    op.drop_table('op_diagnosis_master')
    op.drop_index(op.f('ix_op_complaints_master_is_deleted'), table_name='op_complaints_master')
    op.drop_index(op.f('ix_op_complaints_master_id'), table_name='op_complaints_master')
    op.drop_index(op.f('ix_op_complaints_master_created_at'), table_name='op_complaints_master')
    op.drop_index(op.f('ix_op_complaints_master_complaint'), table_name='op_complaints_master')
    op.drop_index(op.f('ix_op_complaints_master_code'), table_name='op_complaints_master')
    op.drop_index(op.f('ix_op_complaints_master_category'), table_name='op_complaints_master')
    op.drop_table('op_complaints_master')
    op.drop_index(op.f('ix_medicine_master_specialization'), table_name='medicine_master')
    op.drop_index('ix_medicine_master_name_active', table_name='medicine_master')
    op.drop_index(op.f('ix_medicine_master_name'), table_name='medicine_master')
    op.drop_index(op.f('ix_medicine_master_is_deleted'), table_name='medicine_master')
    op.drop_index(op.f('ix_medicine_master_is_active'), table_name='medicine_master')
    op.drop_index(op.f('ix_medicine_master_id'), table_name='medicine_master')
    op.drop_index(op.f('ix_medicine_master_created_at'), table_name='medicine_master')
    op.drop_index('ix_medicine_master_code_spec', table_name='medicine_master')
    op.drop_index(op.f('ix_medicine_master_code'), table_name='medicine_master')
    op.drop_index('ix_medicine_master_category_spec', table_name='medicine_master')
    op.drop_index(op.f('ix_medicine_master_category'), table_name='medicine_master')
    op.drop_table('medicine_master')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_is_deleted'), table_name='departments')
    op.drop_index(op.f('ix_departments_is_active'), table_name='departments')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_created_at'), table_name='departments')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
