"""add_master_data_tables

Revision ID: 4257e363d9e7
Revises: fix_queue_status_enum
Create Date: 2026-02-18 13:44:26.684630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4257e363d9e7'
down_revision: Union[str, None] = 'fix_queue_status_enum'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('op_complaints_master',
    sa.Column('code', sa.String(length=50), nullable=False, comment='Unique complaint code'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='Broad category of the complaint'),
    sa.Column('complaint', sa.String(length=255), nullable=False, comment='The complaint description'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_op_complaints_master_category'), 'op_complaints_master', ['category'], unique=False)
    op.create_index(op.f('ix_op_complaints_master_code'), 'op_complaints_master', ['code'], unique=True)
    op.create_index(op.f('ix_op_complaints_master_complaint'), 'op_complaints_master', ['complaint'], unique=False)
    op.create_index(op.f('ix_op_complaints_master_created_at'), 'op_complaints_master', ['created_at'], unique=False)
    op.create_index(op.f('ix_op_complaints_master_id'), 'op_complaints_master', ['id'], unique=False)
    op.create_index(op.f('ix_op_complaints_master_is_deleted'), 'op_complaints_master', ['is_deleted'], unique=False)
    op.create_table('op_diagnosis_master',
    sa.Column('code', sa.String(length=50), nullable=False, comment='Unique diagnosis code'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='Broad category of the diagnosis'),
    sa.Column('diagnosis', sa.String(length=255), nullable=False, comment='The diagnosis description'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_op_diagnosis_master_category'), 'op_diagnosis_master', ['category'], unique=False)
    op.create_index(op.f('ix_op_diagnosis_master_code'), 'op_diagnosis_master', ['code'], unique=True)
    op.create_index(op.f('ix_op_diagnosis_master_created_at'), 'op_diagnosis_master', ['created_at'], unique=False)
    op.create_index(op.f('ix_op_diagnosis_master_diagnosis'), 'op_diagnosis_master', ['diagnosis'], unique=False)
    op.create_index(op.f('ix_op_diagnosis_master_id'), 'op_diagnosis_master', ['id'], unique=False)
    op.create_index(op.f('ix_op_diagnosis_master_is_deleted'), 'op_diagnosis_master', ['is_deleted'], unique=False)
    op.create_table('op_labtests_master',
    sa.Column('code', sa.String(length=50), nullable=False, comment='Unique lab test code'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='Broad category of the lab test'),
    sa.Column('test_name', sa.String(length=255), nullable=False, comment='The lab test name'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_op_labtests_master_category'), 'op_labtests_master', ['category'], unique=False)
    op.create_index(op.f('ix_op_labtests_master_code'), 'op_labtests_master', ['code'], unique=True)
    op.create_index(op.f('ix_op_labtests_master_created_at'), 'op_labtests_master', ['created_at'], unique=False)
    op.create_index(op.f('ix_op_labtests_master_id'), 'op_labtests_master', ['id'], unique=False)
    op.create_index(op.f('ix_op_labtests_master_is_deleted'), 'op_labtests_master', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_op_labtests_master_test_name'), 'op_labtests_master', ['test_name'], unique=False)
    op.alter_column('appointments', 'waiting_time_minutes',
               existing_type=sa.INTEGER(),
               comment='Calculated waiting time in minutes (based on queue position)',
               existing_comment='Waiting time in minutes',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('appointments', 'buffer_time_minutes',
               existing_type=sa.INTEGER(),
               comment="Extra buffer time added to this patient's consultation slot",
               existing_comment='Extra buffer time added to this patient consultation slot',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('lab_queue_items', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pending', 'waiting', 'in-progress', 'completed', 'cancelled', name='queue_status_enum', native_enum=False),
               existing_comment='Queue item status',
               existing_nullable=False,
               existing_server_default=sa.text("'waiting'::character varying"))
    op.alter_column('pharmacy_queue_items', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pending', 'waiting', 'in-progress', 'completed', 'cancelled', name='queue_status_enum', native_enum=False),
               existing_comment='Queue item status',
               existing_nullable=False,
               existing_server_default=sa.text("'waiting'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pharmacy_queue_items', 'status',
               existing_type=sa.Enum('pending', 'waiting', 'in-progress', 'completed', 'cancelled', name='queue_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_comment='Queue item status',
               existing_nullable=False,
               existing_server_default=sa.text("'waiting'::character varying"))
    op.alter_column('lab_queue_items', 'status',
               existing_type=sa.Enum('pending', 'waiting', 'in-progress', 'completed', 'cancelled', name='queue_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_comment='Queue item status',
               existing_nullable=False,
               existing_server_default=sa.text("'waiting'::character varying"))
    op.alter_column('appointments', 'buffer_time_minutes',
               existing_type=sa.INTEGER(),
               comment='Extra buffer time added to this patient consultation slot',
               existing_comment="Extra buffer time added to this patient's consultation slot",
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('appointments', 'waiting_time_minutes',
               existing_type=sa.INTEGER(),
               comment='Waiting time in minutes',
               existing_comment='Calculated waiting time in minutes (based on queue position)',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_op_labtests_master_test_name'), table_name='op_labtests_master')
    op.drop_index(op.f('ix_op_labtests_master_is_deleted'), table_name='op_labtests_master')
    op.drop_index(op.f('ix_op_labtests_master_id'), table_name='op_labtests_master')
    op.drop_index(op.f('ix_op_labtests_master_created_at'), table_name='op_labtests_master')
    op.drop_index(op.f('ix_op_labtests_master_code'), table_name='op_labtests_master')
    op.drop_index(op.f('ix_op_labtests_master_category'), table_name='op_labtests_master')
    op.drop_table('op_labtests_master')
    op.drop_index(op.f('ix_op_diagnosis_master_is_deleted'), table_name='op_diagnosis_master')
    op.drop_index(op.f('ix_op_diagnosis_master_id'), table_name='op_diagnosis_master')
    op.drop_index(op.f('ix_op_diagnosis_master_diagnosis'), table_name='op_diagnosis_master')
    op.drop_index(op.f('ix_op_diagnosis_master_created_at'), table_name='op_diagnosis_master')
    op.drop_index(op.f('ix_op_diagnosis_master_code'), table_name='op_diagnosis_master')
    op.drop_index(op.f('ix_op_diagnosis_master_category'), table_name='op_diagnosis_master')
    op.drop_table('op_diagnosis_master')
    op.drop_index(op.f('ix_op_complaints_master_is_deleted'), table_name='op_complaints_master')
    op.drop_index(op.f('ix_op_complaints_master_id'), table_name='op_complaints_master')
    op.drop_index(op.f('ix_op_complaints_master_created_at'), table_name='op_complaints_master')
    op.drop_index(op.f('ix_op_complaints_master_complaint'), table_name='op_complaints_master')
    op.drop_index(op.f('ix_op_complaints_master_code'), table_name='op_complaints_master')
    op.drop_index(op.f('ix_op_complaints_master_category'), table_name='op_complaints_master')
    op.drop_table('op_complaints_master')
    # ### end Alembic commands ###
