"""Add patient_documents table

Revision ID: 1db140240fad
Revises: 003
Create Date: 2026-02-05 11:54:50.123662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1db140240fad'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'op_number',
               existing_type=sa.VARCHAR(length=20),
               comment='Outpatient Number (OP-YYYYMMDD-XXX format)',
               existing_nullable=False)
    op.alter_column('appointments', 'patient_id',
               existing_type=sa.UUID(),
               comment='Link to patient',
               existing_nullable=False)
    op.alter_column('appointments', 'doctor_id',
               existing_type=sa.UUID(),
               comment='Assigned doctor',
               existing_nullable=True)
    op.alter_column('appointments', 'appointment_date',
               existing_type=sa.DATE(),
               comment='Appointment date',
               existing_nullable=False)
    op.alter_column('appointments', 'appointment_time',
               existing_type=postgresql.TIME(),
               comment='Scheduled appointment time',
               existing_nullable=True)
    op.alter_column('appointments', 'token_number',
               existing_type=sa.INTEGER(),
               comment='Daily token/queue number',
               existing_nullable=False)
    op.alter_column('appointments', 'status',
               existing_type=postgresql.ENUM('waiting', 'in-progress', 'completed', 'cancelled', name='appointment_status_enum'),
               type_=sa.Enum('waiting', 'in-progress', 'completed', 'cancelled', name='appointment_status_enum', native_enum=False),
               comment='Current appointment status',
               existing_nullable=False,
               existing_server_default=sa.text("'waiting'::appointment_status_enum"))
    op.alter_column('appointments', 'queue_type',
               existing_type=postgresql.ENUM('main', 'lab', 'pharmacy', name='queue_type_enum'),
               type_=sa.Enum('main', 'lab', 'pharmacy', name='queue_type_enum', native_enum=False),
               comment='Which queue this appointment is in',
               existing_nullable=False,
               existing_server_default=sa.text("'main'::queue_type_enum"))
    op.alter_column('appointments', 'room',
               existing_type=sa.VARCHAR(length=20),
               comment='Consultation room number',
               existing_nullable=True)
    op.alter_column('appointments', 'waiting_time_minutes',
               existing_type=sa.INTEGER(),
               comment='Waiting time in minutes',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('appointments', 'called_at',
               existing_type=sa.VARCHAR(length=50),
               comment='When patient was called (status → in-progress)',
               existing_nullable=True)
    op.alter_column('appointments', 'completed_at',
               existing_type=sa.VARCHAR(length=50),
               comment='When consultation completed',
               existing_nullable=True)
    op.alter_column('appointments', 'notes',
               existing_type=sa.VARCHAR(length=500),
               comment='Additional notes',
               existing_nullable=True)
    op.drop_constraint(op.f('appointments_op_number_key'), 'appointments', type_='unique')
    op.drop_index(op.f('ix_appointments_date'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_op_number'), table_name='appointments')
    op.create_index(op.f('ix_appointments_op_number'), 'appointments', ['op_number'], unique=True)
    op.create_index(op.f('ix_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_created_at'), 'appointments', ['created_at'], unique=False)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_index(op.f('ix_appointments_is_deleted'), 'appointments', ['is_deleted'], unique=False)
    op.create_index('ix_appointments_patient_date', 'appointments', ['patient_id', 'appointment_date'], unique=False)
    op.alter_column('bill_line_items', 'bill_id',
               existing_type=sa.UUID(),
               comment='Link to parent bill',
               existing_nullable=False)
    op.alter_column('bill_line_items', 'item_type',
               existing_type=postgresql.ENUM('consultation', 'lab', 'pharmacy', 'procedure', 'other', name='bill_item_type_enum'),
               type_=sa.Enum('consultation', 'lab', 'pharmacy', 'procedure', 'other', name='bill_item_type_enum', native_enum=False),
               comment='Type of item',
               existing_nullable=False,
               existing_server_default=sa.text("'other'::bill_item_type_enum"))
    op.alter_column('bill_line_items', 'item_name',
               existing_type=sa.VARCHAR(length=200),
               comment='Item description',
               existing_nullable=False)
    op.alter_column('bill_line_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Quantity',
               existing_nullable=False,
               existing_server_default=sa.text('1.00'))
    op.alter_column('bill_line_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Price per unit',
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('bill_line_items', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Total amount (quantity * unit_price)',
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.create_index(op.f('ix_bill_line_items_created_at'), 'bill_line_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_bill_line_items_id'), 'bill_line_items', ['id'], unique=False)
    op.create_index(op.f('ix_bill_line_items_is_deleted'), 'bill_line_items', ['is_deleted'], unique=False)
    op.alter_column('bills', 'bill_number',
               existing_type=sa.VARCHAR(length=20),
               comment='Bill number (BLL-YYYYMMDD-XXX format)',
               existing_nullable=False)
    op.alter_column('bills', 'appointment_id',
               existing_type=sa.UUID(),
               comment='Link to appointment',
               existing_nullable=True)
    op.alter_column('bills', 'patient_id',
               existing_type=sa.UUID(),
               comment='Link to patient',
               existing_nullable=False)
    op.alter_column('bills', 'created_by',
               existing_type=sa.UUID(),
               comment='Staff who created the bill',
               existing_nullable=True)
    op.alter_column('bills', 'uhid',
               existing_type=sa.VARCHAR(length=50),
               comment='Unique Hospital ID',
               existing_nullable=True)
    op.alter_column('bills', 'patient_name',
               existing_type=sa.VARCHAR(length=200),
               comment='Patient name for receipt',
               existing_nullable=False)
    op.alter_column('bills', 'patient_age',
               existing_type=sa.VARCHAR(length=10),
               comment='Patient age for receipt',
               existing_nullable=True)
    op.alter_column('bills', 'patient_gender',
               existing_type=sa.VARCHAR(length=10),
               comment='Patient gender for receipt',
               existing_nullable=True)
    op.alter_column('bills', 'doctor_name',
               existing_type=sa.VARCHAR(length=200),
               comment='Doctor name for receipt',
               existing_nullable=True)
    op.alter_column('bills', 'speciality',
               existing_type=sa.VARCHAR(length=100),
               comment='Department/speciality',
               existing_nullable=True)
    op.alter_column('bills', 'mobile_no',
               existing_type=sa.VARCHAR(length=15),
               comment='Patient mobile for receipt',
               existing_nullable=True)
    op.alter_column('bills', 'patient_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Patient type',
               existing_nullable=True)
    op.alter_column('bills', 'token_number',
               existing_type=sa.VARCHAR(length=20),
               comment='Token/OP number',
               existing_nullable=True)
    op.alter_column('bills', 'consultation_fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Consultation fee',
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('bills', 'other_charges',
               existing_type=sa.VARCHAR(length=200),
               comment='Description of other charges',
               existing_nullable=True)
    op.alter_column('bills', 'subtotal',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Subtotal before discount',
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('bills', 'discount_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Discount amount',
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('bills', 'discount_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Discount percentage',
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('bills', 'discount_given_by',
               existing_type=sa.VARCHAR(length=100),
               comment='Who authorized the discount',
               existing_nullable=True)
    op.alter_column('bills', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Total amount after discount',
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('bills', 'paid_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Amount paid',
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('bills', 'due_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Amount due',
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('bills', 'payment_status',
               existing_type=postgresql.ENUM('pending', 'partial', 'paid', name='payment_status_enum'),
               type_=sa.Enum('pending', 'partial', 'paid', name='payment_status_enum', native_enum=False),
               comment='Payment status',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::payment_status_enum"))
    op.alter_column('bills', 'payment_method',
               existing_type=postgresql.ENUM('cash', 'card', 'upi', name='payment_method_enum'),
               type_=sa.Enum('cash', 'card', 'upi', name='payment_method_enum', native_enum=False),
               comment='Payment method used',
               existing_nullable=True)
    op.alter_column('bills', 'payment_reference',
               existing_type=sa.VARCHAR(length=100),
               comment='Transaction reference number',
               existing_nullable=True)
    op.alter_column('bills', 'insurance_provider',
               existing_type=sa.VARCHAR(length=100),
               comment='Insurance provider name',
               existing_nullable=True)
    op.alter_column('bills', 'insurance_policy_number',
               existing_type=sa.VARCHAR(length=100),
               comment='Insurance policy number',
               existing_nullable=True)
    op.drop_constraint(op.f('bills_appointment_id_key'), 'bills', type_='unique')
    op.drop_constraint(op.f('bills_bill_number_key'), 'bills', type_='unique')
    op.drop_index(op.f('ix_bills_bill_number'), table_name='bills')
    op.create_index(op.f('ix_bills_bill_number'), 'bills', ['bill_number'], unique=True)
    op.create_index(op.f('ix_bills_appointment_id'), 'bills', ['appointment_id'], unique=True)
    op.create_index('ix_bills_created_at_status', 'bills', ['created_at', 'payment_status'], unique=False)
    op.create_index(op.f('ix_bills_id'), 'bills', ['id'], unique=False)
    op.create_index(op.f('ix_bills_is_deleted'), 'bills', ['is_deleted'], unique=False)
    op.create_index('ix_bills_patient_created', 'bills', ['patient_id', 'created_at'], unique=False)
    op.alter_column('departments', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Department name (e.g., Cardiology)',
               existing_nullable=False)
    op.alter_column('departments', 'code',
               existing_type=sa.VARCHAR(length=20),
               comment='Short code (e.g., CARD)',
               existing_nullable=False)
    op.alter_column('departments', 'description',
               existing_type=sa.VARCHAR(length=500),
               comment='Department description',
               existing_nullable=True)
    op.alter_column('departments', 'base_consultation_fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Default consultation fee for this department',
               existing_nullable=False,
               existing_server_default=sa.text('300.00'))
    op.alter_column('departments', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Whether department is active',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(op.f('departments_code_key'), 'departments', type_='unique')
    op.drop_constraint(op.f('departments_name_key'), 'departments', type_='unique')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_index(op.f('ix_departments_created_at'), 'departments', ['created_at'], unique=False)
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_is_deleted'), 'departments', ['is_deleted'], unique=False)
    op.alter_column('doctors', 'user_id',
               existing_type=sa.UUID(),
               comment='Link to user account for authentication',
               existing_nullable=True)
    op.alter_column('doctors', 'department_id',
               existing_type=sa.UUID(),
               comment="Doctor's primary department",
               existing_nullable=True)
    op.alter_column('doctors', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='Full name with title (e.g., Dr. R. Balaji)',
               existing_nullable=False)
    op.alter_column('doctors', 'speciality',
               existing_type=sa.VARCHAR(length=100),
               comment='Medical speciality',
               existing_nullable=True)
    op.alter_column('doctors', 'qualification',
               existing_type=sa.VARCHAR(length=200),
               comment='Medical qualifications (e.g., MBBS, MD)',
               existing_nullable=True)
    op.alter_column('doctors', 'registration_number',
               existing_type=sa.VARCHAR(length=50),
               comment='Medical council registration number',
               existing_nullable=True)
    op.alter_column('doctors', 'phone',
               existing_type=sa.VARCHAR(length=15),
               comment='Contact phone number',
               existing_nullable=True)
    op.alter_column('doctors', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Professional email',
               existing_nullable=True)
    op.alter_column('doctors', 'room',
               existing_type=sa.VARCHAR(length=20),
               comment='Default consultation room',
               existing_nullable=True)
    op.alter_column('doctors', 'consultation_fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Override consultation fee (null = use department fee)',
               existing_nullable=True)
    op.alter_column('doctors', 'is_available',
               existing_type=sa.BOOLEAN(),
               comment='Whether doctor is currently available for consultations',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(op.f('doctors_user_id_key'), 'doctors', type_='unique')
    op.drop_index(op.f('ix_doctors_user_id'), table_name='doctors')
    op.create_index(op.f('ix_doctors_user_id'), 'doctors', ['user_id'], unique=True)
    op.create_index(op.f('ix_doctors_created_at'), 'doctors', ['created_at'], unique=False)
    op.create_index(op.f('ix_doctors_id'), 'doctors', ['id'], unique=False)
    op.create_index(op.f('ix_doctors_is_deleted'), 'doctors', ['is_deleted'], unique=False)
    op.alter_column('lab_queue_items', 'appointment_id',
               existing_type=sa.UUID(),
               comment='Link to appointment',
               existing_nullable=False)
    op.alter_column('lab_queue_items', 'patient_id',
               existing_type=sa.UUID(),
               comment='Link to patient',
               existing_nullable=False)
    op.alter_column('lab_queue_items', 'patient_name',
               existing_type=sa.VARCHAR(length=200),
               comment='Patient name for display',
               existing_nullable=False)
    op.alter_column('lab_queue_items', 'mr_number',
               existing_type=sa.VARCHAR(length=20),
               comment='MR number for display',
               existing_nullable=False)
    op.alter_column('lab_queue_items', 'op_number',
               existing_type=sa.VARCHAR(length=20),
               comment='OP number for display',
               existing_nullable=False)
    op.alter_column('lab_queue_items', 'token_number',
               existing_type=sa.INTEGER(),
               comment='Lab queue token number',
               existing_nullable=False)
    op.alter_column('lab_queue_items', 'lab_tests',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='List of lab tests to perform',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('lab_queue_items', 'status',
               existing_type=postgresql.ENUM('waiting', 'in-progress', 'completed', name='queue_status_enum'),
               comment='Queue item status',
               existing_nullable=False,
               existing_server_default=sa.text("'waiting'::queue_status_enum"))
    op.alter_column('lab_queue_items', 'collected_at',
               existing_type=sa.VARCHAR(length=50),
               comment='When sample was collected',
               existing_nullable=True)
    op.alter_column('lab_queue_items', 'completed_at',
               existing_type=sa.VARCHAR(length=50),
               comment='When results were ready',
               existing_nullable=True)
    op.alter_column('lab_queue_items', 'notes',
               existing_type=sa.TEXT(),
               comment='Additional notes',
               existing_nullable=True)
    op.drop_index(op.f('ix_lab_queue_items_created_status'), table_name='lab_queue_items')
    op.create_index('ix_lab_queue_created_status', 'lab_queue_items', ['created_at', 'status'], unique=False)
    op.create_index(op.f('ix_lab_queue_items_created_at'), 'lab_queue_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_lab_queue_items_id'), 'lab_queue_items', ['id'], unique=False)
    op.create_index(op.f('ix_lab_queue_items_is_deleted'), 'lab_queue_items', ['is_deleted'], unique=False)
    op.alter_column('patient_documents', 'patient_id',
               existing_type=sa.UUID(),
               comment='Link to patient',
               existing_nullable=False)
    op.alter_column('patient_documents', 'appointment_id',
               existing_type=sa.UUID(),
               comment='Optional link to appointment',
               existing_nullable=True)
    op.alter_column('patient_documents', 'uploaded_by',
               existing_type=sa.UUID(),
               comment='User who uploaded the document',
               existing_nullable=True)
    op.alter_column('patient_documents', 'file_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Original file name',
               existing_nullable=False)
    op.alter_column('patient_documents', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               comment='Storage path or URL',
               existing_nullable=False)
    op.alter_column('patient_documents', 'file_type',
               existing_type=sa.VARCHAR(length=100),
               comment='MIME type',
               existing_nullable=False)
    op.alter_column('patient_documents', 'file_size',
               existing_type=sa.INTEGER(),
               comment='File size in bytes',
               existing_nullable=False)
    op.alter_column('patient_documents', 'document_type',
               existing_type=sa.VARCHAR(length=100),
               comment='Document category (lab report, prescription, etc.)',
               existing_nullable=True)
    op.alter_column('patient_documents', 'description',
               existing_type=sa.TEXT(),
               comment='Document description',
               existing_nullable=True)
    op.create_index(op.f('ix_patient_documents_created_at'), 'patient_documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_patient_documents_id'), 'patient_documents', ['id'], unique=False)
    op.create_index(op.f('ix_patient_documents_is_deleted'), 'patient_documents', ['is_deleted'], unique=False)
    op.alter_column('patient_vitals', 'appointment_id',
               existing_type=sa.UUID(),
               comment='Link to appointment',
               existing_nullable=False)
    op.alter_column('patient_vitals', 'patient_id',
               existing_type=sa.UUID(),
               comment='Link to patient',
               existing_nullable=False)
    op.alter_column('patient_vitals', 'recorded_by',
               existing_type=sa.UUID(),
               comment='Staff who recorded vitals',
               existing_nullable=True)
    op.alter_column('patient_vitals', 'spo2',
               existing_type=sa.INTEGER(),
               comment='Oxygen saturation percentage',
               existing_nullable=True)
    op.alter_column('patient_vitals', 'pulse',
               existing_type=sa.INTEGER(),
               comment='Pulse rate (beats per minute)',
               existing_nullable=False)
    op.alter_column('patient_vitals', 'blood_pressure',
               existing_type=sa.VARCHAR(length=20),
               comment='Blood pressure (format: systolic/diastolic)',
               existing_nullable=False)
    op.alter_column('patient_vitals', 'cvs',
               existing_type=sa.VARCHAR(length=100),
               comment='Cardiovascular system findings',
               existing_nullable=True)
    op.alter_column('patient_vitals', 'rs',
               existing_type=sa.VARCHAR(length=100),
               comment='Respiratory system findings',
               existing_nullable=True)
    op.alter_column('patient_vitals', 'jvp',
               existing_type=sa.VARCHAR(length=50),
               comment='Jugular venous pressure',
               existing_nullable=True)
    op.alter_column('patient_vitals', 'weight',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Weight in kg',
               existing_nullable=True)
    op.alter_column('patient_vitals', 'hlp',
               existing_type=sa.VARCHAR(length=50),
               comment='Hyperlipidemia status',
               existing_nullable=True)
    op.alter_column('patient_vitals', 'htn',
               existing_type=sa.VARCHAR(length=50),
               comment='Hypertension status',
               existing_nullable=True)
    op.alter_column('patient_vitals', 'dm',
               existing_type=sa.VARCHAR(length=50),
               comment='Diabetes mellitus status',
               existing_nullable=True)
    op.alter_column('patient_vitals', 'smoking',
               existing_type=sa.VARCHAR(length=50),
               comment='Smoking status',
               existing_nullable=True)
    op.alter_column('patient_vitals', 'family_ho_cad',
               existing_type=sa.VARCHAR(length=100),
               comment='Family history of coronary artery disease',
               existing_nullable=True)
    op.alter_column('patient_vitals', 'heart_disease',
               existing_type=sa.VARCHAR(length=100),
               comment='Known heart disease',
               existing_nullable=True)
    op.alter_column('patient_vitals', 'ptca_cabg',
               existing_type=sa.VARCHAR(length=100),
               comment='Previous PTCA/CABG procedures',
               existing_nullable=True)
    op.alter_column('patient_vitals', 'current_drugs',
               existing_type=sa.TEXT(),
               comment='Current medications',
               existing_nullable=True)
    op.drop_constraint(op.f('patient_vitals_appointment_id_key'), 'patient_vitals', type_='unique')
    op.drop_index(op.f('ix_patient_vitals_appointment_id'), table_name='patient_vitals')
    op.create_index(op.f('ix_patient_vitals_appointment_id'), 'patient_vitals', ['appointment_id'], unique=True)
    op.create_index(op.f('ix_patient_vitals_created_at'), 'patient_vitals', ['created_at'], unique=False)
    op.create_index(op.f('ix_patient_vitals_id'), 'patient_vitals', ['id'], unique=False)
    op.create_index(op.f('ix_patient_vitals_is_deleted'), 'patient_vitals', ['is_deleted'], unique=False)
    op.alter_column('patients', 'mr_number',
               existing_type=sa.VARCHAR(length=20),
               comment='Medical Record Number (MR-XXXXX format)',
               existing_nullable=False)
    op.alter_column('patients', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Patient first name',
               existing_nullable=False)
    op.alter_column('patients', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Patient last name',
               existing_nullable=False)
    op.alter_column('patients', 'date_of_birth',
               existing_type=sa.DATE(),
               comment='Date of birth',
               existing_nullable=True)
    op.alter_column('patients', 'gender',
               existing_type=postgresql.ENUM('Male', 'Female', 'Other', name='gender_enum'),
               type_=sa.Enum('Male', 'Female', 'Other', name='gender_enum', native_enum=False),
               comment='Patient gender',
               existing_nullable=False)
    op.alter_column('patients', 'marital_status',
               existing_type=postgresql.ENUM('Single', 'Married', 'Divorced', 'Widowed', name='marital_status_enum'),
               type_=sa.Enum('Single', 'Married', 'Divorced', 'Widowed', name='marital_status_enum', native_enum=False),
               comment='Marital status',
               existing_nullable=True)
    op.alter_column('patients', 'patient_type',
               existing_type=postgresql.ENUM('New', 'Review', 'Emergency', 'Referral', name='patient_type_enum'),
               type_=sa.Enum('New', 'Review', 'Emergency', 'Referral', name='patient_type_enum', native_enum=False),
               comment='Patient type',
               existing_nullable=True)
    op.alter_column('patients', 'phone',
               existing_type=sa.VARCHAR(length=15),
               comment='Primary phone (Indian format)',
               existing_nullable=False)
    op.alter_column('patients', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Email address',
               existing_nullable=True)
    op.alter_column('patients', 'emergency_contact',
               existing_type=sa.VARCHAR(length=15),
               comment='Emergency contact phone',
               existing_nullable=True)
    op.alter_column('patients', 'address',
               existing_type=sa.TEXT(),
               comment='Street address',
               existing_nullable=True)
    op.alter_column('patients', 'city',
               existing_type=sa.VARCHAR(length=100),
               comment='City',
               existing_nullable=True)
    op.alter_column('patients', 'state',
               existing_type=sa.VARCHAR(length=100),
               comment='State',
               existing_nullable=True)
    op.alter_column('patients', 'pin_code',
               existing_type=sa.VARCHAR(length=10),
               comment='PIN code',
               existing_nullable=True)
    op.alter_column('patients', 'blood_group',
               existing_type=sa.VARCHAR(length=10),
               comment='Blood group',
               existing_nullable=True)
    op.drop_constraint(op.f('patients_mr_number_key'), 'patients', type_='unique')
    op.drop_index(op.f('ix_patients_mr_number'), table_name='patients')
    op.create_index(op.f('ix_patients_mr_number'), 'patients', ['mr_number'], unique=True)
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_index(op.f('ix_patients_is_deleted'), 'patients', ['is_deleted'], unique=False)
    op.alter_column('pharmacy_queue_items', 'appointment_id',
               existing_type=sa.UUID(),
               comment='Link to appointment',
               existing_nullable=False)
    op.alter_column('pharmacy_queue_items', 'patient_id',
               existing_type=sa.UUID(),
               comment='Link to patient',
               existing_nullable=False)
    op.alter_column('pharmacy_queue_items', 'patient_name',
               existing_type=sa.VARCHAR(length=200),
               comment='Patient name for display',
               existing_nullable=False)
    op.alter_column('pharmacy_queue_items', 'mr_number',
               existing_type=sa.VARCHAR(length=20),
               comment='MR number for display',
               existing_nullable=False)
    op.alter_column('pharmacy_queue_items', 'op_number',
               existing_type=sa.VARCHAR(length=20),
               comment='OP number for display',
               existing_nullable=False)
    op.alter_column('pharmacy_queue_items', 'token_number',
               existing_type=sa.INTEGER(),
               comment='Pharmacy queue token number',
               existing_nullable=False)
    op.alter_column('pharmacy_queue_items', 'medicines',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='List of medicines to dispense',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('pharmacy_queue_items', 'status',
               existing_type=postgresql.ENUM('waiting', 'in-progress', 'completed', name='queue_status_enum'),
               comment='Queue item status',
               existing_nullable=False,
               existing_server_default=sa.text("'waiting'::queue_status_enum"))
    op.alter_column('pharmacy_queue_items', 'dispensed_at',
               existing_type=sa.VARCHAR(length=50),
               comment='When medicines were dispensed',
               existing_nullable=True)
    op.alter_column('pharmacy_queue_items', 'completed_at',
               existing_type=sa.VARCHAR(length=50),
               comment='When patient collected medicines',
               existing_nullable=True)
    op.alter_column('pharmacy_queue_items', 'notes',
               existing_type=sa.TEXT(),
               comment='Additional notes',
               existing_nullable=True)
    op.drop_index(op.f('ix_pharmacy_queue_items_created_status'), table_name='pharmacy_queue_items')
    op.create_index('ix_pharmacy_queue_created_status', 'pharmacy_queue_items', ['created_at', 'status'], unique=False)
    op.create_index(op.f('ix_pharmacy_queue_items_created_at'), 'pharmacy_queue_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_pharmacy_queue_items_id'), 'pharmacy_queue_items', ['id'], unique=False)
    op.create_index(op.f('ix_pharmacy_queue_items_is_deleted'), 'pharmacy_queue_items', ['is_deleted'], unique=False)
    op.alter_column('prescription_medicines', 'prescription_id',
               existing_type=sa.UUID(),
               comment='Link to prescription',
               existing_nullable=False)
    op.alter_column('prescription_medicines', 'medicine_name',
               existing_type=sa.VARCHAR(length=200),
               comment='Medicine name',
               existing_nullable=False)
    op.alter_column('prescription_medicines', 'dosage',
               existing_type=sa.VARCHAR(length=100),
               comment='Dosage (e.g., 10mg)',
               existing_nullable=True)
    op.alter_column('prescription_medicines', 'frequency',
               existing_type=sa.VARCHAR(length=50),
               comment='Frequency (e.g., 1-0-1)',
               existing_nullable=True)
    op.alter_column('prescription_medicines', 'duration',
               existing_type=sa.VARCHAR(length=50),
               comment='Duration (e.g., 30 days)',
               existing_nullable=True)
    op.alter_column('prescription_medicines', 'instructions',
               existing_type=sa.VARCHAR(length=200),
               comment='Special instructions',
               existing_nullable=True)
    op.alter_column('prescription_medicines', 'sequence_order',
               existing_type=sa.INTEGER(),
               comment='Order in prescription',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_prescription_medicines_created_at'), 'prescription_medicines', ['created_at'], unique=False)
    op.create_index(op.f('ix_prescription_medicines_id'), 'prescription_medicines', ['id'], unique=False)
    op.create_index(op.f('ix_prescription_medicines_is_deleted'), 'prescription_medicines', ['is_deleted'], unique=False)
    op.alter_column('prescriptions', 'patient_id',
               existing_type=sa.UUID(),
               comment='Link to patient',
               existing_nullable=False)
    op.alter_column('prescriptions', 'appointment_id',
               existing_type=sa.UUID(),
               comment='Link to appointment',
               existing_nullable=False)
    op.alter_column('prescriptions', 'doctor_id',
               existing_type=sa.UUID(),
               comment='Prescribing doctor',
               existing_nullable=True)
    op.alter_column('prescriptions', 'diagnosis',
               existing_type=sa.TEXT(),
               comment='Primary diagnosis',
               existing_nullable=False)
    op.alter_column('prescriptions', 'complaint',
               existing_type=sa.TEXT(),
               comment='Chief complaint',
               existing_nullable=True)
    op.alter_column('prescriptions', 'history',
               existing_type=sa.TEXT(),
               comment='Relevant history',
               existing_nullable=True)
    op.alter_column('prescriptions', 'lab_tests',
               existing_type=sa.TEXT(),
               comment='Ordered lab tests',
               existing_nullable=True)
    op.alter_column('prescriptions', 'advice',
               existing_type=sa.TEXT(),
               comment='Medical advice',
               existing_nullable=True)
    op.alter_column('prescriptions', 'notes',
               existing_type=sa.TEXT(),
               comment='Additional notes',
               existing_nullable=True)
    op.alter_column('prescriptions', 'follow_up_days',
               existing_type=sa.INTEGER(),
               comment='Follow-up after X days',
               existing_nullable=True)
    op.alter_column('prescriptions', 'sent_to_patient',
               existing_type=sa.BOOLEAN(),
               comment='Whether sent to patient',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('prescriptions', 'sent_via',
               existing_type=sa.VARCHAR(length=20),
               comment='Delivery method (whatsapp/email)',
               existing_nullable=True)
    op.drop_constraint(op.f('prescriptions_appointment_id_key'), 'prescriptions', type_='unique')
    op.drop_index(op.f('ix_prescriptions_appointment_id'), table_name='prescriptions')
    op.create_index(op.f('ix_prescriptions_appointment_id'), 'prescriptions', ['appointment_id'], unique=True)
    op.create_index(op.f('ix_prescriptions_created_at'), 'prescriptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_prescriptions_id'), 'prescriptions', ['id'], unique=False)
    op.create_index(op.f('ix_prescriptions_is_deleted'), 'prescriptions', ['is_deleted'], unique=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('front-office', 'doctor', name='user_role'),
               type_=sa.Enum('front-office', 'doctor', name='user_role', native_enum=False),
               existing_comment='User role determining access permissions',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('front-office', 'doctor', name='user_role', native_enum=False),
               type_=postgresql.ENUM('front-office', 'doctor', name='user_role'),
               existing_comment='User role determining access permissions',
               existing_nullable=False)
    op.drop_index(op.f('ix_prescriptions_is_deleted'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_created_at'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_appointment_id'), table_name='prescriptions')
    op.create_index(op.f('ix_prescriptions_appointment_id'), 'prescriptions', ['appointment_id'], unique=False)
    op.create_unique_constraint(op.f('prescriptions_appointment_id_key'), 'prescriptions', ['appointment_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('prescriptions', 'sent_via',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Delivery method (whatsapp/email)',
               existing_nullable=True)
    op.alter_column('prescriptions', 'sent_to_patient',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether sent to patient',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('prescriptions', 'follow_up_days',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Follow-up after X days',
               existing_nullable=True)
    op.alter_column('prescriptions', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Additional notes',
               existing_nullable=True)
    op.alter_column('prescriptions', 'advice',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Medical advice',
               existing_nullable=True)
    op.alter_column('prescriptions', 'lab_tests',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Ordered lab tests',
               existing_nullable=True)
    op.alter_column('prescriptions', 'history',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Relevant history',
               existing_nullable=True)
    op.alter_column('prescriptions', 'complaint',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Chief complaint',
               existing_nullable=True)
    op.alter_column('prescriptions', 'diagnosis',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Primary diagnosis',
               existing_nullable=False)
    op.alter_column('prescriptions', 'doctor_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Prescribing doctor',
               existing_nullable=True)
    op.alter_column('prescriptions', 'appointment_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Link to appointment',
               existing_nullable=False)
    op.alter_column('prescriptions', 'patient_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Link to patient',
               existing_nullable=False)
    op.drop_index(op.f('ix_prescription_medicines_is_deleted'), table_name='prescription_medicines')
    op.drop_index(op.f('ix_prescription_medicines_id'), table_name='prescription_medicines')
    op.drop_index(op.f('ix_prescription_medicines_created_at'), table_name='prescription_medicines')
    op.alter_column('prescription_medicines', 'sequence_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Order in prescription',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('prescription_medicines', 'instructions',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Special instructions',
               existing_nullable=True)
    op.alter_column('prescription_medicines', 'duration',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Duration (e.g., 30 days)',
               existing_nullable=True)
    op.alter_column('prescription_medicines', 'frequency',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Frequency (e.g., 1-0-1)',
               existing_nullable=True)
    op.alter_column('prescription_medicines', 'dosage',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Dosage (e.g., 10mg)',
               existing_nullable=True)
    op.alter_column('prescription_medicines', 'medicine_name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Medicine name',
               existing_nullable=False)
    op.alter_column('prescription_medicines', 'prescription_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Link to prescription',
               existing_nullable=False)
    op.drop_index(op.f('ix_pharmacy_queue_items_is_deleted'), table_name='pharmacy_queue_items')
    op.drop_index(op.f('ix_pharmacy_queue_items_id'), table_name='pharmacy_queue_items')
    op.drop_index(op.f('ix_pharmacy_queue_items_created_at'), table_name='pharmacy_queue_items')
    op.drop_index('ix_pharmacy_queue_created_status', table_name='pharmacy_queue_items')
    op.create_index(op.f('ix_pharmacy_queue_items_created_status'), 'pharmacy_queue_items', ['created_at', 'status'], unique=False)
    op.alter_column('pharmacy_queue_items', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Additional notes',
               existing_nullable=True)
    op.alter_column('pharmacy_queue_items', 'completed_at',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='When patient collected medicines',
               existing_nullable=True)
    op.alter_column('pharmacy_queue_items', 'dispensed_at',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='When medicines were dispensed',
               existing_nullable=True)
    op.alter_column('pharmacy_queue_items', 'status',
               existing_type=postgresql.ENUM('waiting', 'in-progress', 'completed', name='queue_status_enum'),
               comment=None,
               existing_comment='Queue item status',
               existing_nullable=False,
               existing_server_default=sa.text("'waiting'::queue_status_enum"))
    op.alter_column('pharmacy_queue_items', 'medicines',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='List of medicines to dispense',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('pharmacy_queue_items', 'token_number',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Pharmacy queue token number',
               existing_nullable=False)
    op.alter_column('pharmacy_queue_items', 'op_number',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='OP number for display',
               existing_nullable=False)
    op.alter_column('pharmacy_queue_items', 'mr_number',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='MR number for display',
               existing_nullable=False)
    op.alter_column('pharmacy_queue_items', 'patient_name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Patient name for display',
               existing_nullable=False)
    op.alter_column('pharmacy_queue_items', 'patient_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Link to patient',
               existing_nullable=False)
    op.alter_column('pharmacy_queue_items', 'appointment_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Link to appointment',
               existing_nullable=False)
    op.drop_index(op.f('ix_patients_is_deleted'), table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_mr_number'), table_name='patients')
    op.create_index(op.f('ix_patients_mr_number'), 'patients', ['mr_number'], unique=False)
    op.create_unique_constraint(op.f('patients_mr_number_key'), 'patients', ['mr_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('patients', 'blood_group',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Blood group',
               existing_nullable=True)
    op.alter_column('patients', 'pin_code',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='PIN code',
               existing_nullable=True)
    op.alter_column('patients', 'state',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='State',
               existing_nullable=True)
    op.alter_column('patients', 'city',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='City',
               existing_nullable=True)
    op.alter_column('patients', 'address',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Street address',
               existing_nullable=True)
    op.alter_column('patients', 'emergency_contact',
               existing_type=sa.VARCHAR(length=15),
               comment=None,
               existing_comment='Emergency contact phone',
               existing_nullable=True)
    op.alter_column('patients', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Email address',
               existing_nullable=True)
    op.alter_column('patients', 'phone',
               existing_type=sa.VARCHAR(length=15),
               comment=None,
               existing_comment='Primary phone (Indian format)',
               existing_nullable=False)
    op.alter_column('patients', 'patient_type',
               existing_type=sa.Enum('New', 'Review', 'Emergency', 'Referral', name='patient_type_enum', native_enum=False),
               type_=postgresql.ENUM('New', 'Review', 'Emergency', 'Referral', name='patient_type_enum'),
               comment=None,
               existing_comment='Patient type',
               existing_nullable=True)
    op.alter_column('patients', 'marital_status',
               existing_type=sa.Enum('Single', 'Married', 'Divorced', 'Widowed', name='marital_status_enum', native_enum=False),
               type_=postgresql.ENUM('Single', 'Married', 'Divorced', 'Widowed', name='marital_status_enum'),
               comment=None,
               existing_comment='Marital status',
               existing_nullable=True)
    op.alter_column('patients', 'gender',
               existing_type=sa.Enum('Male', 'Female', 'Other', name='gender_enum', native_enum=False),
               type_=postgresql.ENUM('Male', 'Female', 'Other', name='gender_enum'),
               comment=None,
               existing_comment='Patient gender',
               existing_nullable=False)
    op.alter_column('patients', 'date_of_birth',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date of birth',
               existing_nullable=True)
    op.alter_column('patients', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Patient last name',
               existing_nullable=False)
    op.alter_column('patients', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Patient first name',
               existing_nullable=False)
    op.alter_column('patients', 'mr_number',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Medical Record Number (MR-XXXXX format)',
               existing_nullable=False)
    op.drop_index(op.f('ix_patient_vitals_is_deleted'), table_name='patient_vitals')
    op.drop_index(op.f('ix_patient_vitals_id'), table_name='patient_vitals')
    op.drop_index(op.f('ix_patient_vitals_created_at'), table_name='patient_vitals')
    op.drop_index(op.f('ix_patient_vitals_appointment_id'), table_name='patient_vitals')
    op.create_index(op.f('ix_patient_vitals_appointment_id'), 'patient_vitals', ['appointment_id'], unique=False)
    op.create_unique_constraint(op.f('patient_vitals_appointment_id_key'), 'patient_vitals', ['appointment_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('patient_vitals', 'current_drugs',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Current medications',
               existing_nullable=True)
    op.alter_column('patient_vitals', 'ptca_cabg',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Previous PTCA/CABG procedures',
               existing_nullable=True)
    op.alter_column('patient_vitals', 'heart_disease',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Known heart disease',
               existing_nullable=True)
    op.alter_column('patient_vitals', 'family_ho_cad',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Family history of coronary artery disease',
               existing_nullable=True)
    op.alter_column('patient_vitals', 'smoking',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Smoking status',
               existing_nullable=True)
    op.alter_column('patient_vitals', 'dm',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Diabetes mellitus status',
               existing_nullable=True)
    op.alter_column('patient_vitals', 'htn',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Hypertension status',
               existing_nullable=True)
    op.alter_column('patient_vitals', 'hlp',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Hyperlipidemia status',
               existing_nullable=True)
    op.alter_column('patient_vitals', 'weight',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='Weight in kg',
               existing_nullable=True)
    op.alter_column('patient_vitals', 'jvp',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Jugular venous pressure',
               existing_nullable=True)
    op.alter_column('patient_vitals', 'rs',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Respiratory system findings',
               existing_nullable=True)
    op.alter_column('patient_vitals', 'cvs',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Cardiovascular system findings',
               existing_nullable=True)
    op.alter_column('patient_vitals', 'blood_pressure',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Blood pressure (format: systolic/diastolic)',
               existing_nullable=False)
    op.alter_column('patient_vitals', 'pulse',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Pulse rate (beats per minute)',
               existing_nullable=False)
    op.alter_column('patient_vitals', 'spo2',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Oxygen saturation percentage',
               existing_nullable=True)
    op.alter_column('patient_vitals', 'recorded_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Staff who recorded vitals',
               existing_nullable=True)
    op.alter_column('patient_vitals', 'patient_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Link to patient',
               existing_nullable=False)
    op.alter_column('patient_vitals', 'appointment_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Link to appointment',
               existing_nullable=False)
    op.drop_index(op.f('ix_patient_documents_is_deleted'), table_name='patient_documents')
    op.drop_index(op.f('ix_patient_documents_id'), table_name='patient_documents')
    op.drop_index(op.f('ix_patient_documents_created_at'), table_name='patient_documents')
    op.alter_column('patient_documents', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Document description',
               existing_nullable=True)
    op.alter_column('patient_documents', 'document_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Document category (lab report, prescription, etc.)',
               existing_nullable=True)
    op.alter_column('patient_documents', 'file_size',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='File size in bytes',
               existing_nullable=False)
    op.alter_column('patient_documents', 'file_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='MIME type',
               existing_nullable=False)
    op.alter_column('patient_documents', 'file_path',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Storage path or URL',
               existing_nullable=False)
    op.alter_column('patient_documents', 'file_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Original file name',
               existing_nullable=False)
    op.alter_column('patient_documents', 'uploaded_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User who uploaded the document',
               existing_nullable=True)
    op.alter_column('patient_documents', 'appointment_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Optional link to appointment',
               existing_nullable=True)
    op.alter_column('patient_documents', 'patient_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Link to patient',
               existing_nullable=False)
    op.drop_index(op.f('ix_lab_queue_items_is_deleted'), table_name='lab_queue_items')
    op.drop_index(op.f('ix_lab_queue_items_id'), table_name='lab_queue_items')
    op.drop_index(op.f('ix_lab_queue_items_created_at'), table_name='lab_queue_items')
    op.drop_index('ix_lab_queue_created_status', table_name='lab_queue_items')
    op.create_index(op.f('ix_lab_queue_items_created_status'), 'lab_queue_items', ['created_at', 'status'], unique=False)
    op.alter_column('lab_queue_items', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Additional notes',
               existing_nullable=True)
    op.alter_column('lab_queue_items', 'completed_at',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='When results were ready',
               existing_nullable=True)
    op.alter_column('lab_queue_items', 'collected_at',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='When sample was collected',
               existing_nullable=True)
    op.alter_column('lab_queue_items', 'status',
               existing_type=postgresql.ENUM('waiting', 'in-progress', 'completed', name='queue_status_enum'),
               comment=None,
               existing_comment='Queue item status',
               existing_nullable=False,
               existing_server_default=sa.text("'waiting'::queue_status_enum"))
    op.alter_column('lab_queue_items', 'lab_tests',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='List of lab tests to perform',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('lab_queue_items', 'token_number',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Lab queue token number',
               existing_nullable=False)
    op.alter_column('lab_queue_items', 'op_number',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='OP number for display',
               existing_nullable=False)
    op.alter_column('lab_queue_items', 'mr_number',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='MR number for display',
               existing_nullable=False)
    op.alter_column('lab_queue_items', 'patient_name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Patient name for display',
               existing_nullable=False)
    op.alter_column('lab_queue_items', 'patient_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Link to patient',
               existing_nullable=False)
    op.alter_column('lab_queue_items', 'appointment_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Link to appointment',
               existing_nullable=False)
    op.drop_index(op.f('ix_doctors_is_deleted'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_created_at'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_user_id'), table_name='doctors')
    op.create_index(op.f('ix_doctors_user_id'), 'doctors', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('doctors_user_id_key'), 'doctors', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('doctors', 'is_available',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether doctor is currently available for consultations',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('doctors', 'consultation_fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Override consultation fee (null = use department fee)',
               existing_nullable=True)
    op.alter_column('doctors', 'room',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Default consultation room',
               existing_nullable=True)
    op.alter_column('doctors', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Professional email',
               existing_nullable=True)
    op.alter_column('doctors', 'phone',
               existing_type=sa.VARCHAR(length=15),
               comment=None,
               existing_comment='Contact phone number',
               existing_nullable=True)
    op.alter_column('doctors', 'registration_number',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Medical council registration number',
               existing_nullable=True)
    op.alter_column('doctors', 'qualification',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Medical qualifications (e.g., MBBS, MD)',
               existing_nullable=True)
    op.alter_column('doctors', 'speciality',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Medical speciality',
               existing_nullable=True)
    op.alter_column('doctors', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Full name with title (e.g., Dr. R. Balaji)',
               existing_nullable=False)
    op.alter_column('doctors', 'department_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment="Doctor's primary department",
               existing_nullable=True)
    op.alter_column('doctors', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Link to user account for authentication',
               existing_nullable=True)
    op.drop_index(op.f('ix_departments_is_deleted'), table_name='departments')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_created_at'), table_name='departments')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=False)
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=False)
    op.create_unique_constraint(op.f('departments_name_key'), 'departments', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('departments_code_key'), 'departments', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('departments', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether department is active',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('departments', 'base_consultation_fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Default consultation fee for this department',
               existing_nullable=False,
               existing_server_default=sa.text('300.00'))
    op.alter_column('departments', 'description',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Department description',
               existing_nullable=True)
    op.alter_column('departments', 'code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Short code (e.g., CARD)',
               existing_nullable=False)
    op.alter_column('departments', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Department name (e.g., Cardiology)',
               existing_nullable=False)
    op.drop_index('ix_bills_patient_created', table_name='bills')
    op.drop_index(op.f('ix_bills_is_deleted'), table_name='bills')
    op.drop_index(op.f('ix_bills_id'), table_name='bills')
    op.drop_index('ix_bills_created_at_status', table_name='bills')
    op.drop_index(op.f('ix_bills_appointment_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_bill_number'), table_name='bills')
    op.create_index(op.f('ix_bills_bill_number'), 'bills', ['bill_number'], unique=False)
    op.create_unique_constraint(op.f('bills_bill_number_key'), 'bills', ['bill_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('bills_appointment_id_key'), 'bills', ['appointment_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('bills', 'insurance_policy_number',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Insurance policy number',
               existing_nullable=True)
    op.alter_column('bills', 'insurance_provider',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Insurance provider name',
               existing_nullable=True)
    op.alter_column('bills', 'payment_reference',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Transaction reference number',
               existing_nullable=True)
    op.alter_column('bills', 'payment_method',
               existing_type=sa.Enum('cash', 'card', 'upi', name='payment_method_enum', native_enum=False),
               type_=postgresql.ENUM('cash', 'card', 'upi', name='payment_method_enum'),
               comment=None,
               existing_comment='Payment method used',
               existing_nullable=True)
    op.alter_column('bills', 'payment_status',
               existing_type=sa.Enum('pending', 'partial', 'paid', name='payment_status_enum', native_enum=False),
               type_=postgresql.ENUM('pending', 'partial', 'paid', name='payment_status_enum'),
               comment=None,
               existing_comment='Payment status',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::payment_status_enum"))
    op.alter_column('bills', 'due_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Amount due',
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('bills', 'paid_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Amount paid',
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('bills', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Total amount after discount',
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('bills', 'discount_given_by',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Who authorized the discount',
               existing_nullable=True)
    op.alter_column('bills', 'discount_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='Discount percentage',
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('bills', 'discount_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Discount amount',
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('bills', 'subtotal',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Subtotal before discount',
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('bills', 'other_charges',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Description of other charges',
               existing_nullable=True)
    op.alter_column('bills', 'consultation_fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Consultation fee',
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('bills', 'token_number',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Token/OP number',
               existing_nullable=True)
    op.alter_column('bills', 'patient_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Patient type',
               existing_nullable=True)
    op.alter_column('bills', 'mobile_no',
               existing_type=sa.VARCHAR(length=15),
               comment=None,
               existing_comment='Patient mobile for receipt',
               existing_nullable=True)
    op.alter_column('bills', 'speciality',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Department/speciality',
               existing_nullable=True)
    op.alter_column('bills', 'doctor_name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Doctor name for receipt',
               existing_nullable=True)
    op.alter_column('bills', 'patient_gender',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Patient gender for receipt',
               existing_nullable=True)
    op.alter_column('bills', 'patient_age',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Patient age for receipt',
               existing_nullable=True)
    op.alter_column('bills', 'patient_name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Patient name for receipt',
               existing_nullable=False)
    op.alter_column('bills', 'uhid',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Unique Hospital ID',
               existing_nullable=True)
    op.alter_column('bills', 'created_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Staff who created the bill',
               existing_nullable=True)
    op.alter_column('bills', 'patient_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Link to patient',
               existing_nullable=False)
    op.alter_column('bills', 'appointment_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Link to appointment',
               existing_nullable=True)
    op.alter_column('bills', 'bill_number',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Bill number (BLL-YYYYMMDD-XXX format)',
               existing_nullable=False)
    op.drop_index(op.f('ix_bill_line_items_is_deleted'), table_name='bill_line_items')
    op.drop_index(op.f('ix_bill_line_items_id'), table_name='bill_line_items')
    op.drop_index(op.f('ix_bill_line_items_created_at'), table_name='bill_line_items')
    op.alter_column('bill_line_items', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Total amount (quantity * unit_price)',
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('bill_line_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Price per unit',
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('bill_line_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Quantity',
               existing_nullable=False,
               existing_server_default=sa.text('1.00'))
    op.alter_column('bill_line_items', 'item_name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Item description',
               existing_nullable=False)
    op.alter_column('bill_line_items', 'item_type',
               existing_type=sa.Enum('consultation', 'lab', 'pharmacy', 'procedure', 'other', name='bill_item_type_enum', native_enum=False),
               type_=postgresql.ENUM('consultation', 'lab', 'pharmacy', 'procedure', 'other', name='bill_item_type_enum'),
               comment=None,
               existing_comment='Type of item',
               existing_nullable=False,
               existing_server_default=sa.text("'other'::bill_item_type_enum"))
    op.alter_column('bill_line_items', 'bill_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Link to parent bill',
               existing_nullable=False)
    op.drop_index('ix_appointments_patient_date', table_name='appointments')
    op.drop_index(op.f('ix_appointments_is_deleted'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_created_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_date'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_op_number'), table_name='appointments')
    op.create_index(op.f('ix_appointments_op_number'), 'appointments', ['op_number'], unique=False)
    op.create_index(op.f('ix_appointments_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_unique_constraint(op.f('appointments_op_number_key'), 'appointments', ['op_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('appointments', 'notes',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Additional notes',
               existing_nullable=True)
    op.alter_column('appointments', 'completed_at',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='When consultation completed',
               existing_nullable=True)
    op.alter_column('appointments', 'called_at',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='When patient was called (status → in-progress)',
               existing_nullable=True)
    op.alter_column('appointments', 'waiting_time_minutes',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Waiting time in minutes',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('appointments', 'room',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Consultation room number',
               existing_nullable=True)
    op.alter_column('appointments', 'queue_type',
               existing_type=sa.Enum('main', 'lab', 'pharmacy', name='queue_type_enum', native_enum=False),
               type_=postgresql.ENUM('main', 'lab', 'pharmacy', name='queue_type_enum'),
               comment=None,
               existing_comment='Which queue this appointment is in',
               existing_nullable=False,
               existing_server_default=sa.text("'main'::queue_type_enum"))
    op.alter_column('appointments', 'status',
               existing_type=sa.Enum('waiting', 'in-progress', 'completed', 'cancelled', name='appointment_status_enum', native_enum=False),
               type_=postgresql.ENUM('waiting', 'in-progress', 'completed', 'cancelled', name='appointment_status_enum'),
               comment=None,
               existing_comment='Current appointment status',
               existing_nullable=False,
               existing_server_default=sa.text("'waiting'::appointment_status_enum"))
    op.alter_column('appointments', 'token_number',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Daily token/queue number',
               existing_nullable=False)
    op.alter_column('appointments', 'appointment_time',
               existing_type=postgresql.TIME(),
               comment=None,
               existing_comment='Scheduled appointment time',
               existing_nullable=True)
    op.alter_column('appointments', 'appointment_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Appointment date',
               existing_nullable=False)
    op.alter_column('appointments', 'doctor_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Assigned doctor',
               existing_nullable=True)
    op.alter_column('appointments', 'patient_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Link to patient',
               existing_nullable=False)
    op.alter_column('appointments', 'op_number',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Outpatient Number (OP-YYYYMMDD-XXX format)',
               existing_nullable=False)
    # ### end Alembic commands ###
